sdk:
  - pubspec
  - dev
  - stable

stages:
  - analyze:
      - format:
        sdk:
          - pubspec
      - analyze: --fatal-infos .
  - build:
      - command: dart run build_runner build --fail-on-severe
  - unit_test:
      - command: dart run build_runner test --fail-on-severe -- -P ci
