name: angular
repository: https://github.com/angulardart-community/angular

packages:
   - "**"
  # - ngast
  # - ngcompiler
  # - ngdart
  # - ngforms
  # - ngrouter
  # - ngtest

ignore:
  # - _tests
  - examples
  - tests

command:
  bootstrap:
    usePubspecOverrides: true
