name: angular_workspace
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  - ngast
  - ngcompiler
  - ngdart
  - ngforms
  - ngrouter
  - ngtest

  - examples/hello_world

  - _tests
  - goldens

dev_dependencies:
  lints: ^5.1.0
  melos: ^6.2.0
