// Mocks generated by Mockito 5.4.3 from annotations
// in ngrouter/test/regression/hash_location_strategy_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:html' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:ngrouter/src/location/browser_platform_location.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocation_0 extends _i1.SmartFake implements _i2.Location {
  _FakeLocation_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BrowserPlatformLocation].
///
/// See the documentation for Mockito's code generation for more information.
class MockBrowserPlatformLocation extends _i1.Mock
    implements _i3.BrowserPlatformLocation {
  @override
  _i2.Location get location => (super.noSuchMethod(
        Invocation.getter(#location),
        returnValue: _FakeLocation_0(
          this,
          Invocation.getter(#location),
        ),
        returnValueForMissingStub: _FakeLocation_0(
          this,
          Invocation.getter(#location),
        ),
      ) as _i2.Location);

  @override
  String get pathname => (super.noSuchMethod(
        Invocation.getter(#pathname),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#pathname),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#pathname),
        ),
      ) as String);

  @override
  String get search => (super.noSuchMethod(
        Invocation.getter(#search),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#search),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#search),
        ),
      ) as String);

  @override
  String get hash => (super.noSuchMethod(
        Invocation.getter(#hash),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#hash),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#hash),
        ),
      ) as String);

  @override
  set pathname(String? newPath) => super.noSuchMethod(
        Invocation.setter(
          #pathname,
          newPath,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPopState(_i2.EventListener? fn) => super.noSuchMethod(
        Invocation.method(
          #onPopState,
          [fn],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onHashChange(_i2.EventListener? fn) => super.noSuchMethod(
        Invocation.method(
          #onHashChange,
          [fn],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pushState(
    Object? state,
    String? title,
    String? url,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #pushState,
          [
            state,
            title,
            url,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void replaceState(
    Object? state,
    String? title,
    String? url,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #replaceState,
          [
            state,
            title,
            url,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void forward() => super.noSuchMethod(
        Invocation.method(
          #forward,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void back() => super.noSuchMethod(
        Invocation.method(
          #back,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
